; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
board = nanoatmega328new
platform = atmelavr
framework = arduino
lib_deps = 
	rfetick/MPU6050_light@^1.1.0
	pololu/VL6180X@^1.4.0
	olikraus/U8g2@^2.36.18
monitor_speed = 9600
upload_speed = 115200
build_flags = -Os -Wall -Wextra -std=gnu++17
build_unflags = -std=gnu++11
build_src_flags = -Os -Wall -Werror -Wextra
extra_scripts = pre:configure_platform.py
